--- a/Makefile
+++ b/Makefile
@@ -2,18 +2,24 @@
 DEP	=	dep
 EXE = ${OBJ}/bin
 
-COMMIT := $(shell git log -1 --pretty=format:"%H")
+UNAME := $(shell uname -m)
+
+COMMON_CFLAGS = -fcf-protection=full -O3 -std=gnu11 -Wall -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
+COMMON_LDFLAGS = -Wl,-z,relro -Wl,-z,now -Wall -ggdb -rdynamic -Wl,--as-needed -lm -lrt -lcrypto -lz -lpthread
 
-ARCH =
-ifeq ($m, 32)
-ARCH = -m32
-endif
-ifeq ($m, 64)
 ARCH = -m64
+ifeq ($(UNAME), x86_64)
+CFLAGS = $(COMMON_CFLAGS) -mpclmul -march=core2 -mfpmath=sse -mssse3
+else ifeq ($(UNAME), i686)
+CFLAGS = $(COMMON_CFLAGS)
+ARCH = -m32
+else ifeq ($(UNAME), aarch64)
+CFLAGS = $(COMMON_CFLAGS)
+else ifeq ($(UNAME), arm7h)
+CFLAGS = $(COMMON_CFLAGS)
 endif
 
-CFLAGS = $(ARCH) -O3 -std=gnu11 -Wall -mpclmul -march=core2 -mfpmath=sse -mssse3 -fno-strict-aliasing -fno-strict-overflow -fwrapv -DAES=1 -DCOMMIT=\"${COMMIT}\" -D_GNU_SOURCE=1 -D_FILE_OFFSET_BITS=64
-LDFLAGS = $(ARCH) -ggdb -rdynamic -lm -lrt -lcrypto -lz -lpthread -lcrypto
+LDFLAGS = $(COMMON_LDFLAGS)
 
 LIB = ${OBJ}/lib
 CINCLUDE = -iquote common -iquote .
