name: Check builds

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      matrix:
        workdir:
          - wl-gears-git
          - linux-ck-autobuild
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git
          pwd
          ls -la
          git submodule update ${{ matrix.workdir }}
      - name: Build package
        run: makepkg -si
        working-directory: ${{ matrix.workdir }}
